### PR TITLE
Add crypto ticker support

### PR DESCRIPTION
**Pull request by shtirlic**

### CODE REVIEW

**Comment by shtirlic** [comment]
Oh shi.... I just found tmux-crypto ;)

**Comment by Brutuski** [comment]
> Oh shi.... I just found tmux-crypto ;)

Well that is more specific, supports more fiat currencies and such.
There is an open issue there to add a portfolio option, take a stab at that if you would like
https://github.com/Brutuski/tmux-crypto/issues/2

tmux-ticker on the other hand was envisioned more for traditional markets, though I can see the benefit of adding a ticker for a crypto in here.
For people who tend to stick to only the traditional market and wouldn't mind seeing what btc is doing these days since it's all over the news.

**Comment by shtirlic** [comment]
Yeah, it's great to have the base support for all the assest in one place like: BTC, index and fav stock.

**Comment by Brutuski** [comment]
> Yeah, it's great to have the base support for all the assest in one place like: BTC, index and fav stock.

Agreed. Not everyone needs a dedicated plugin for just 1 thing.

**Pull request merged**
